import React, { useEffect, useMemo, useRef, useState } from 'react';
import { View, Text, StyleSheet, ScrollView, Pressable, TextInput, Image, useWindowDimensions, Alert } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import Animated, { FadeIn, FadeInUp } from 'react-native-reanimated';
import GridBackground from '../components/GridBackground';
import ArtBand from '../components/ArtBand';
import CoachPresence from '../components/CoachPresence';
const BOOTS = require('../../assets/art/scan-boots.jpg');
import { Coach } from '../data/coaches';
import {
  BASELINE_SCRIPTS,
  BASELINE_DAYS,
  BASELINE_DAY_INTRO,
  BASELINE_MATCHES,
  BASELINE_MOMENT_MIN_ANSWER,
  BASELINE_MOMENT_QUESTIONS,
  BASELINE_MOMENT_TAGS,
  BaselineAnalysisKey,
  BaselineDayStatus,
  BaselineMatchStats,
  BaselineMoment,
  BaselineSession,
  baselineStatsComplete,
  beatKey,
  currentBaselineDay,
  dayStatus,
  isBaselineMatchDay,
  isBaselineRestDay,
  isWeekComplete,
  loadBaseline,
  matchNumberForDay,
  momentAskFor,
  recordBaselineMatch,
  saveBaselineReflection,
  sealBaseline,
  sealBaselineDay,
  tendenciesOf,
  weekMoments,
} from '../data/baselineScan';
import { getSettings } from '../data/settings';
import { COMPOSURE_LABELS, resultOf } from '../data/matches';
import { CheckIcon, EyeIcon } from '../components/Icons';
import HonestyBadge from '../components/HonestyBadge';
import { isValidReflection } from '../data/honestyGuard';
import { sfx } from '../audio/sound';
import { colors, monoFont, displayFont, bodyFont, bodyFontHeavy, gradeColor } from '../theme';
const MIN_ANSWER = 12;
type Phase = 'talk' | 'day' | 'reflection' | 'ambition' | 'card';
type DayStep = 'start' | 'match' | 'stats' | 'review' | 'analysis' | 'dayq';
interface DraftMoment { id: string; name: string; startMin: number; endMin: number; tag: string | null; analysis: Partial<Record<BaselineAnalysisKey, string>>; }
function Stepper({ value, onChange, accent }: { value: number; onChange: (n: number) => void; accent?: boolean }) {
  return (<View style={styles.stepper}><Pressable onPress={() => onChange(Math.max(0, value - 1))} hitSlop={10} style={styles.stepBtn}><Text style={styles.stepBtnTxt}>−</Text></Pressable><Text style={[styles.stepValue, accent && { color: colors.primary }]}>{value}</Text><Pressable onPress={() => onChange(Math.min(9, value + 1))} hitSlop={10} style={styles.stepBtn}><Text style={styles.stepBtnTxt}>+</Text></Pressable></View>);
}
function WeekStrip({ session }: { session: BaselineSession | null }) {
  return (<View style={styles.weekStrip}>{Array.from({ length: BASELINE_DAYS }).map((_, i) => {
    const day = i + 1; const st: BaselineDayStatus = dayStatus(session, day);
    const pill = st === 'done' ? styles.dayPillDone : st === 'today' ? styles.dayPillNow : st === 'locked' ? styles.dayPillLocked : styles.dayPillFuture;
    const txt = st === 'done' ? styles.dayPillTxtDone : st === 'today' ? styles.dayPillTxtNow : styles.dayPillTxtMuted;
    return (<View key={day} style={[styles.dayPill, pill]}><Text style={[styles.dayPillTxt, txt]}>{day}</Text></View>);
  })}</View>);
}
const REFLECTION_STARTERS: Partial<Record<BaselineAnalysisKey, string[]>> = {
  feel: ['PRESSURE', 'PANIC', 'FRUSTRATION', 'RUSHED', 'CALM', 'CONFIDENT', 'ANGRY', 'UNCERTAIN'],
  cause: ['FORCED PASS', 'LOSS OF FOCUS', 'RUSHING', 'POOR POSITIONING', 'PANIC', 'MISREAD THE PLAY', 'FATIGUE', 'OTHER'],
};
const GUIDE_KEY = 'psa.baseline.guide.v1';
const GUIDE_STEPS = [
  ['YOUR WEEK MAP', 'These seven markers show completed days, today, and what is still ahead. You will play five matches; Days 4 and 6 are intentional rest and reflection days.'],
  ['WHAT TO DO FIRST', 'Start with a normal match. Record it if you can, then come back while the key moments are fresh. You are not trying to create a perfect result.'],
  ['TYPE THE TRUTH', 'After the final whistle, open the console stats screen and TYPE every number you see. We could scan it — but typing is the hard way. AI hallucinates. You don’t.'],
  ['KEEP GOING WHEN READY', 'Each completed day adds evidence to your starting card. Seal a day and continue straight to the next one whenever you want.'],
] as const;
function BaselineGuide({ index, onNext, onBack, onSkip }: { index: number; onNext: () => void; onBack: () => void; onSkip: () => void }) {
  const [title, body] = GUIDE_STEPS[index];
  return <View style={styles.guideBox} accessibilityRole="summary"><Text style={styles.guideArrow}>↓</Text><View style={styles.guideCopy}><Text style={styles.guideKicker}>QUICK TOUR · {index + 1}/{GUIDE_STEPS.length}</Text><Text style={styles.guideTitle}>{title}</Text><Text style={styles.guideBody}>{body}</Text></View><View style={styles.guideActions}>{index > 0 && <Pressable onPress={onBack} hitSlop={8}><Text style={styles.guideBack}>‹ BACK</Text></Pressable>}<Pressable onPress={onNext} style={styles.guideNext}><Text style={styles.guideNextTxt}>{index === GUIDE_STEPS.length - 1 ? 'GOT IT' : 'NEXT ›'}</Text></Pressable></View><Pressable onPress={onSkip} hitSlop={8}><Text style={styles.guideSkip}>SKIP TOUR</Text></Pressable></View>;
}
function HelpCard({ title = 'WHY WE ASK THIS', children }: { title?: string; children: React.ReactNode }) {
  return <View style={styles.helpCard}><Text style={styles.helpTitle}>?  {title}</Text><Text style={styles.helpText}>{children}</Text></View>;
}
function momentComplete(m: DraftMoment): boolean {
  return BASELINE_MOMENT_QUESTIONS.every((q) => (m.analysis[q.key] ?? '').trim().length >= BASELINE_MOMENT_MIN_ANSWER);
}
function StatInput({ label, hint, value, onChange, suffix }: { label: string; hint: string; value: string; onChange: (v: string) => void; suffix?: string }) {
  return (<View style={styles.statField}><View style={styles.statFieldHead}><Text style={styles.statLabel}>{label}</Text><Text style={styles.statHint}>{hint}</Text></View><View style={styles.statInputRow}><TextInput value={value} onChangeText={onChange} placeholder="—" placeholderTextColor="rgba(143,184,155,0.35)" keyboardType="number-pad" style={styles.statInput} maxLength={3} /><Text style={styles.statSuffix}>{suffix ?? ''}</Text></View></View>);
}
export default function BaselineScanScreen({ coach, onDone }: { coach: Coach; onDone: () => void }) {
  const { width: winW } = useWindowDimensions();
  const bandW = Math.min(winW, 430);
  const script = useMemo(() => BASELINE_SCRIPTS[coach.id] ?? BASELINE_SCRIPTS.chinedu, [coach.id]);
  const [session, setSession] = useState<BaselineSession | null>(null);
  const [phase, setPhase] = useState<Phase>('talk');
  const [step, setStep] = useState<DayStep>('start');
  const [notReady, setNotReady] = useState(false);
  const scrollRef = useRef<ScrollView>(null);
  const [gf, setGf] = useState(0); const [ga, setGa] = useState(0); const [touched, setTouched] = useState(false);
  const [composure, setComposure] = useState<number | null>(null);
  const [moments, setMoments] = useState<DraftMoment[]>([]); const [dayAnswer, setDayAnswer] = useState('');
  const [momentName, setMomentName] = useState(''); const [momentStart, setMomentStart] = useState(0); const [momentEnd, setMomentEnd] = useState(5);
  const [reflection, setReflection] = useState({ repeated: '', changed: '' }); const [ambition, setAmbition] = useState(''); const [sealing, setSealing] = useState(false);
  const [guideStep, setGuideStep] = useState<number | null>(null); const seq = useRef(1);
  // ── FC 26 stats draft — TYPED, not scanned ──
  const [possession, setPossession] = useState(''); const [shots, setShots] = useState(''); const [shotsOnTarget, setShotsOnTarget] = useState('');
  const [passAcc, setPassAcc] = useState(''); const [corners, setCorners] = useState(''); const [fouls, setFouls] = useState('');
  const [tackles, setTackles] = useState(''); const [saves, setSaves] = useState(''); const [offsides, setOffsides] = useState(''); const [yellowCards, setYellowCards] = useState('');
  const [profilePicUri, setProfilePicUri] = useState<string | null>(null);
  const day = currentBaselineDay(session); const complete = isWeekComplete(session);
  useEffect(() => { void AsyncStorage.getItem(GUIDE_KEY).then((seen) => { if (!seen) setGuideStep(0); }); }, []);
  const dismissGuide = () => { setGuideStep(null); void AsyncStorage.setItem(GUIDE_KEY, 'seen'); };
  useEffect(() => {
    void loadBaseline(coach.id).then((s) => {
      setSession(s);
      if (s.card) setPhase('card');
      else if (currentBaselineDay(s) > BASELINE_DAYS) setPhase('ambition');
      else if (isBaselineRestDay(currentBaselineDay(s))) setPhase('reflection');
      else if (currentBaselineDay(s) > 1 && currentBaselineDay(s) <= BASELINE_DAYS) setPhase('day');
      else setPhase(s.entries.length > 0 ? 'day' : 'talk');
      // restore pending pic if any entry has it
      const pic = [...(s.entries ?? [])].reverse().find((e: any) => e.profilePicUri)?.profilePicUri;
      if (pic) setProfilePicUri(pic);
    });
  }, [coach.id]);
  const first = coach.name.split(' ')[0].toUpperCase();
  const result = resultOf({ gf, ga }); const played = touched || gf > 0 || ga > 0;
  const question = useMemo(() => { const bank = script.questions[result]; return bank[(Math.max(1, day) - 1) % bank.length]; }, [script, result, day]);
  const beat = played ? script.beats[beatKey(gf, ga)] : null;
  const allMomentsDone = moments.length > 0 && moments.every(momentComplete);
  const statsDraft: BaselineMatchStats = useMemo(() => ({
    possession: possession === '' ? null : Math.max(0, Math.min(100, Number(possession))),
    shots: shots === '' ? null : Math.max(0, Math.min(50, Number(shots))),
    shotsOnTarget: shotsOnTarget === '' ? null : Math.max(0, Math.min(50, Number(shotsOnTarget))),
    passAccuracy: passAcc === '' ? null : Math.max(0, Math.min(100, Number(passAcc))),
    corners: corners === '' ? null : Math.max(0, Math.min(30, Number(corners))),
    fouls: fouls === '' ? null : Math.max(0, Math.min(30, Number(fouls))),
    tackles: tackles === '' ? null : Math.max(0, Math.min(50, Number(tackles))),
    saves: saves === '' ? null : Math.max(0, Math.min(20, Number(saves))),
    offsides: offsides === '' ? null : Math.max(0, Math.min(20, Number(offsides))),
    yellowCards: yellowCards === '' ? null : Math.max(0, Math.min(10, Number(yellowCards))),
  }), [possession, shots, shotsOnTarget, passAcc, corners, fouls, tackles, saves, offsides, yellowCards]);
  const statsComplete = baselineStatsComplete(statsDraft);
  const canSealDay = composure !== null && statsComplete && allMomentsDone && isValidReflection(dayAnswer, { minLength: MIN_ANSWER, minWords: 2, prompt: question });
  const pickProfilePic = async () => {
    try {
      const ImagePicker: any = await import('expo-image-picker').catch(() => null);
      if (!ImagePicker) { Alert.alert('Photo unavailable', 'Image picker is not available on this build. You can add a photo later.'); return; }
      const perm = await ImagePicker.requestMediaLibraryPermissionsAsync?.();
      if (perm && perm.status !== 'granted') { Alert.alert('Permission needed', 'Allow photo access to add your profile picture.'); return; }
      const res = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ImagePicker.MediaTypeOptions?.Images ?? 'Images', allowsEditing: true, aspect: [1, 1], quality: 0.7, base64: false });
      if (!res.canceled && res.assets?.[0]?.uri) { sfx('pop'); setProfilePicUri(res.assets[0].uri); }
    } catch { Alert.alert('Photo unavailable', 'Could not open photo library on this device.'); }
  };
  const takeProfilePhoto = async () => {
    try {
      const ImagePicker: any = await import('expo-image-picker').catch(() => null);
      if (!ImagePicker) return;
      const perm = await ImagePicker.requestCameraPermissionsAsync?.();
      if (perm && perm.status !== 'granted') { Alert.alert('Camera permission needed', 'Allow camera access to take a photo.'); return; }
      const res = await ImagePicker.launchCameraAsync({ allowsEditing: true, aspect: [1, 1], quality: 0.7 });
      if (!res.canceled && res.assets?.[0]?.uri) { sfx('pop'); setProfilePicUri(res.assets[0].uri); }
    } catch {}
  };
  const sealDay = () => {
    if (!canSealDay || !session) return;
    sfx('whoosh');
    const filed: BaselineMoment[] = moments.map((m) => ({ id: m.id, name: m.name, startMin: m.startMin, endMin: m.endMin, tag: m.tag, when: `${m.startMin}’–${m.endMin}’`, kind: m.tag ?? 'FAIL MOMENT', answer: (m.analysis.happened ?? '').trim(), analysis: m.analysis }));
    recordBaselineMatch({ gf, ga, result, composure: composure as number, question, answer: dayAnswer.trim(), moments: filed, stats: statsDraft, profilePicUri });
    sealBaselineDay(day);
    setGf(0); setGa(0); setTouched(false); setComposure(null); setMoments([]); setDayAnswer(''); setMomentName(''); setMomentStart(0); setMomentEnd(5);
    setPossession(''); setShots(''); setShotsOnTarget(''); setPassAcc(''); setCorners(''); setFouls(''); setTackles(''); setSaves(''); setOffsides(''); setYellowCards('');
    setStep('start');
    void loadBaseline(coach.id).then((s) => { setSession({ ...s }); const d = currentBaselineDay(s); if (d > BASELINE_DAYS) setPhase('ambition'); else setPhase(isBaselineRestDay(d) ? 'reflection' : 'day'); scrollRef.current?.scrollTo({ y: 0, animated: false }); });
  };
  const sealReflection = () => {
    if (!isValidReflection(reflection.repeated, { minLength: MIN_ANSWER, minWords: 2 }) || !isValidReflection(reflection.changed, { minLength: MIN_ANSWER, minWords: 2 }) || !session) return;
    sfx('whoosh'); saveBaselineReflection(reflection.repeated, reflection.changed); sealBaselineDay(6);
    void loadBaseline(coach.id).then((s) => { setSession({ ...s }); setPhase('day'); });
  };
  const seal = async () => {
    if (!isValidReflection(ambition, { minLength: MIN_ANSWER, minWords: 2 }) || sealing) return;
    setSealing(true);
    const card = await sealBaseline(getSettings().displayName, coach.id, ambition.trim(), profilePicUri);
    sfx('success'); const s = await loadBaseline(coach.id); setSession({ ...s, card }); setPhase('card'); setSealing(false);
  };
  const startMatch = async () => { sfx('whoosh'); setStep('match'); };
  const logScore = () => { sfx('whoosh'); setStep('stats'); };
  const confirmStats = () => { if (!statsComplete) return; sfx('whoosh'); setStep('review'); };
  const addMoment = () => {
    const name = momentName.trim(); if (name.length < 2) return; sfx('pop');
    setMoments((prev) => [...prev, { id: `BM${Date.now().toString(36)}${(seq.current++).toString(36)}`, name, startMin: Math.max(0, Math.min(44, momentStart)), endMin: Math.max(momentStart, Math.min(45, momentEnd)), tag: null, analysis: {} }]);
    setMomentName(''); setMomentEnd(Math.min(45, momentStart + 5));
  };
  const setMomentAnalysis = (id: string, key: BaselineAnalysisKey, text: string) => { setMoments((prev) => prev.map((m) => (m.id === id ? { ...m, analysis: { ...m.analysis, [key]: text } } : m))); };
  const tendencies = useMemo(() => tendenciesOf(session?.entries ?? []), [session]);
  const allWeekMoments = useMemo(() => weekMoments(session), [session]);
  const avgStatsPreview = useMemo(() => { if (!session?.entries?.length) return null; const cur = [...session.entries]; if (statsComplete) cur.push({ gf, ga, result, composure: composure ?? 3, question, answer: dayAnswer, moments: [], stats: statsDraft, at: Date.now() } as any); const avail = cur.filter((e: any) => e.stats && baselineStatsComplete(e.stats)); if (!avail.length) return null; const sum = (k: keyof BaselineMatchStats) => avail.reduce((s: number, e: any) => s + Number(e.stats[k] ?? 0), 0); const a = (k: keyof BaselineMatchStats) => Math.round((sum(k) / avail.length) * 10) / 10; return { possession: a('possession'), passAccuracy: a('passAccuracy'), shots: a('shots'), shotsOnTarget: a('shotsOnTarget') }; }, [session?.entries, statsComplete, statsDraft, gf, ga, result, composure, question, dayAnswer]);
  return (<View style={styles.root}><GridBackground /><ArtBand source={BOOTS} width={bandW} height={118} warmAt={{ x: bandW * 0.3, y: 34, r: bandW * 0.5 }} grain={0.05} />
      <ScrollView ref={scrollRef} style={{ flex: 1 }} contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}>
        <Animated.View key={phase + day} entering={FadeIn.duration(280)}>
          {phase === 'talk' && (<>
              <Text style={styles.eyebrow}>BEFORE YOUR JOURNEY UNLOCKS</Text><Text style={styles.title}>THE BASELINE WEEK</Text><Text style={styles.sub}>ONE MATCH A DAY · SEVEN DAYS · NO SHORTCUTS</Text>
              <View style={styles.coachRow}><CoachPresence size={44}><Image source={coach.portrait} style={styles.coachFace} /></CoachPresence><Text style={styles.coachName}>{first} · ON THE GATE</Text></View>
              {script.talk.map((b, i) => (<Animated.View key={i} entering={FadeInUp.delay(200 + i * 260).duration(300)} style={styles.beat}><View style={[styles.quoteBar, { backgroundColor: coach.cardAccent }]} /><Text style={styles.beatTxt}>{b}</Text></Animated.View>))}
              <Animated.View entering={FadeInUp.delay(200 + script.talk.length * 260).duration(300)} style={styles.bluffBox}><Text style={styles.bluffLabel}>HOW THIS WEEK WORKS</Text><Text style={styles.bluffTxt}>Five ranked matches and two reflection days, walked at your pace. After each match you OPEN the FC 26 post-match stats screen and TYPE every number by hand. We could scan it — but typing IS the work. AI can hallucinate. You don’t. If you can win the small hard way, you can win the big hard way.</Text></Animated.View>
              <Animated.View entering={FadeInUp.delay(200 + (script.talk.length + 1) * 260).duration(300)} style={styles.bluffBox}><Text style={styles.bluffLabel}>THE STATS SCREEN IS THE RECEIPT</Text><Text style={styles.bluffTxt}>Possession • Shots • On Target • Pass Accuracy • Corners • Fouls • Tackles • Saves ( + offsides/yellows if shown). Take a photo of the screen if you want, but type the numbers. That average across 5 matches becomes your baseline card.</Text></Animated.View>
              <Animated.View entering={FadeInUp.delay(200 + (script.talk.length + 2) * 260).duration(300)} style={styles.bluffBox}><Text style={styles.bluffLabel}>HIS HOUSE RULE</Text><Text style={styles.bluffTxt}>“{script.bluff}”</Text></Animated.View>
              <View style={styles.photoPickBox}><Text style={styles.photoPickLabel}>YOUR BASELINE PHOTO (FOR YOUR CARD)</Text><Text style={styles.photoPickHint}>Snap or pick one now, or before you seal Day 7. This photo goes on your sealed baseline card.</Text>{profilePicUri ? <Image source={{ uri: profilePicUri! }} style={styles.photoPreview} /> : <View style={styles.photoPlaceholder}><Text style={styles.photoPlaceholderTxt}>NO PHOTO YET</Text></View>}<View style={styles.photoRow}><Pressable onPress={takeProfilePhoto} style={styles.photoBtn}><Text style={styles.photoBtnTxt}>TAKE PHOTO</Text></Pressable><Pressable onPress={pickProfilePic} style={styles.photoBtnAlt}><Text style={styles.photoBtnAltTxt}>PICK FROM GALLERY</Text></Pressable></View></View>
              <Pressable onPress={() => { sfx('whoosh'); setPhase('day'); setStep('start'); }} style={styles.cta}><Text style={styles.ctaTxt}>I'M IN — START DAY 1</Text></Pressable>
              <Pressable onPress={() => setNotReady((v) => !v)} hitSlop={8}><Text style={styles.skipLink}>{notReady ? 'UNDERSTOOD — THIS GATE STAYS REAL' : 'NOT READY?'}</Text></Pressable>
              {notReady && (<Text style={styles.notReadyTxt}>Then the journey waits. The academy does not remove you for thinking — but it does not carry passengers either. Come back when you mean it; this screen will be here.</Text>)}
            </>)}
          {phase === 'day' && day <= BASELINE_DAYS && (<>
              <Text style={styles.eyebrow}>BASELINE WEEK · DAY {day} OF {BASELINE_DAYS} · MATCH {matchNumberForDay(session, day)} OF {BASELINE_MATCHES}</Text><WeekStrip session={session} />
              {guideStep !== null && <BaselineGuide index={guideStep} onBack={() => setGuideStep(n => Math.max(0, (n ?? 0) - 1))} onNext={() => { if (guideStep >= GUIDE_STEPS.length - 1) dismissGuide(); else setGuideStep(guideStep + 1); }} onSkip={dismissGuide} />}
              <Pressable onPress={() => setGuideStep(0)} hitSlop={8}><Text style={styles.replayGuide}>?  SHOW ME HOW BASELINE WEEK WORKS</Text></Pressable>
              {day > 1 && (<View style={styles.dayIntro}><Image source={coach.portrait} style={styles.beatFace} /><Text style={styles.dayIntroTxt}>{BASELINE_DAY_INTRO[coach.id]?.[day] ?? BASELINE_DAY_INTRO.chinedu?.[day]}</Text></View>)}
              {step === 'start' && (<Animated.View entering={FadeInUp.duration(300)}>
                  <Text style={styles.heroLine}>THE CHINEDU WAY — PEN TO PAPER BEFORE YOU TYPE.</Text>
                  <Text style={styles.heroSub}>1. RECORD & WATCH: Record your console match as usual before kick-off (PS Share / Xbox Capture / capture card), play your match, then watch your tape back.{'\n'}2. PEN TO PAPER: Biro to paper — connection you cannot type. Write your key moments.{'\n'}3. OPEN THE STATS SCREEN: After full time, leave the stats screen on your TV/monitor.{'\n'}4. TYPE THE TRUTH: Open the app and TYPE every number from that screen. No copy-paste. That is the baseline.</Text>
                  <HelpCard title="YOUR MATCH-DAY CHECKLIST">Play normally. When the FT stats screen appears, keep it on screen and switch to the app immediately. Type every number you see — even the ugly ones.</HelpCard>
                  <View style={styles.armNote}><Text style={styles.armNoteTxt}>IN A WORLD LOOKING FOR THE EASY WAY OUT: THE HARD WAY IS THE EASY WAY. IF YOU CAN WIN THE SMALL THINGS BY HAND, YOU CAN WIN THE BIG THINGS.</Text></View>
                  <Pressable onPress={() => void startMatch()} style={[styles.cta, { opacity: 0.95 }]}><Text style={styles.ctaTxt}>I HAVE READ THE RITUAL — START THE MATCH ›</Text></Pressable>
                </Animated.View>)}
              {step === 'match' && (<Animated.View entering={FadeInUp.duration(300)}>
                  <Text style={styles.heroLine}>FULL TIME. LET’S CAPTURE THE MATCH.</Text>
                  <View style={styles.scoreCard}><View style={styles.scoreSide}><Text style={styles.scoreLabel}>YOU</Text><Stepper value={gf} onChange={(n) => { setTouched(true); setGf(n); }} accent={result === 'W'} /></View><View style={[styles.pill, result === 'W' && styles.pillW, result === 'D' && styles.pillD, result === 'L' && styles.pillL]}><Text style={styles.pillTxt}>{result}</Text></View><View style={styles.scoreSide}><Text style={styles.scoreLabel}>THEM</Text><Stepper value={ga} onChange={(n) => { setTouched(true); setGa(n); }} accent={result === 'L'} /></View></View>
                  {beat && (<Animated.View entering={FadeInUp.duration(280)} style={styles.beatBubble}><Image source={coach.portrait} style={styles.beatFace} /><Text style={styles.beatBubbleTxt}>{beat}</Text></Animated.View>)}
                  {played && (<><Text style={styles.fieldLabel}>YOUR HEAD, FULL 90</Text><View style={styles.chipRow}>{COMPOSURE_LABELS.map((label, i) => (<Pressable key={label} onPress={() => setComposure(composure === i + 1 ? null : i + 1)} style={[styles.chip, composure === i + 1 && styles.chipActive]}><Text style={[styles.chipTxt, composure === i + 1 && styles.chipTxtActive]}>{label}</Text></Pressable>))}</View><Pressable onPress={logScore} style={[styles.cta, !played || composure === null ? { opacity: 0.35 } : {}]}><Text style={styles.ctaTxt}>SCORE LOCKED — ENTER THE STATS ›</Text></Pressable>{composure === null && <Text style={styles.requireTxt}>PICK YOUR HEAD STATE FIRST, THEN ENTER THE STATS SCREEN NUMBERS.</Text>}</>)}
                  {!played && <Text style={styles.requireTxt}>SET THE SCORE FIRST — THEN WE MOVE.</Text>}
                </Animated.View>)}
              {step === 'stats' && (<Animated.View entering={FadeInUp.duration(300)}>
                  <Text style={styles.heroLine}>THE STATS SCREEN — TYPE EVERY NUMBER YOU SEE.</Text><Text style={styles.heroSub}>Keep the FC 26 post-match stats screen on your TV. We can scan it, but typing is stronger — AI can hallucinate, you won’t. Small hard way → big hard way.</Text>
                  <HelpCard title="WHAT TO TYPE — TAKE 60 SECONDS">Match stats from the FC 26 screen after full time. Fixture stats are below. Type what YOU see on YOUR side — the screen shows both teams, type YOUR column. If a stat says “—” or is blank, leave it blank for now and we’ll average what you did type.</HelpCard>
                  <View style={styles.statsGrid}>
                    <StatInput label="POSSESSION" hint="YOUR %" value={possession} onChange={(v) => setPossession(v.replace(/[^0-9]/g, '').slice(0, 3))} suffix="%" />
                    <StatInput label="PASS ACCURACY" hint="YOUR %" value={passAcc} onChange={(v) => setPassAcc(v.replace(/[^0-9]/g, '').slice(0, 3))} suffix="%" />
                    <StatInput label="SHOTS" hint="TOTAL" value={shots} onChange={(v) => setShots(v.replace(/[^0-9]/g, '').slice(0, 2))} />
                    <StatInput label="SHOTS ON TARGET" hint="ON TARGET" value={shotsOnTarget} onChange={(v) => setShotsOnTarget(v.replace(/[^0-9]/g, '').slice(0, 2))} />
                    <StatInput label="CORNERS" hint="YOURS" value={corners} onChange={(v) => setCorners(v.replace(/[^0-9]/g, '').slice(0, 2))} />
                    <StatInput label="FOULS" hint="YOU COMMITTED" value={fouls} onChange={(v) => setFouls(v.replace(/[^0-9]/g, '').slice(0, 2))} />
                    <StatInput label="TACKLES" hint="WON" value={tackles} onChange={(v) => setTackles(v.replace(/[^0-9]/g, '').slice(0, 2))} />
                    <StatInput label="SAVES" hint="KEEPER" value={saves} onChange={(v) => setSaves(v.replace(/[^0-9]/g, '').slice(0, 2))} />
                    <StatInput label="OFFSIDES" hint="OPTIONAL" value={offsides} onChange={(v) => setOffsides(v.replace(/[^0-9]/g, '').slice(0, 2))} />
                    <StatInput label="YELLOW CARDS" hint="OPTIONAL" value={yellowCards} onChange={(v) => setYellowCards(v.replace(/[^0-9]/g, '').slice(0, 2))} />
                  </View>
                  <View style={styles.statsNote}><Text style={styles.statsNoteTxt}>REQUIRED: Possession, Shots, On Target, Pass %, Corners, Fouls, Tackles, Saves — 8 numbers. Offsides & Yellows are optional but help your discipline read. Honest typing beats a perfect scan.</Text></View>
                  <View style={styles.photoPickBoxSmall}><Text style={styles.photoPickLabel}>YOUR BASELINE PHOTO (OPTIONAL NOW, REQUIRED BY SEAL)</Text>{profilePicUri ? <Image source={{ uri: profilePicUri! }} style={styles.photoPreviewSmall} /> : <View style={styles.photoPlaceholderSmall}><Text style={styles.photoPlaceholderTxt}>NO PHOTO YET — TAP TO ADD</Text></View>}<View style={styles.photoRow}><Pressable onPress={takeProfilePhoto} style={styles.photoBtnSmall}><Text style={styles.photoBtnTxt}>CAMERA</Text></Pressable><Pressable onPress={pickProfilePic} style={styles.photoBtnAltSmall}><Text style={styles.photoBtnAltTxt}>GALLERY</Text></Pressable></View></View>
                  <Pressable onPress={confirmStats} style={[styles.cta, !statsComplete && { opacity: 0.35 }]}><Text style={styles.ctaTxt}>STATS TYPED — CONTINUE TO MOMENTS ›</Text></Pressable>
                  {!statsComplete && <Text style={styles.requireTxt}>FILL ALL 8 REQUIRED NUMBERS TO CONTINUE. CHECK THE STATS SCREEN AGAIN.</Text>}
                  {avgStatsPreview && <Text style={styles.requireTxt}>RUNNING AVERAGE: {avgStatsPreview.possession}% poss · {avgStatsPreview.passAccuracy}% pass · {avgStatsPreview.shotsOnTarget}/{avgStatsPreview.shots} on target</Text>}
                </Animated.View>)}
              {step === 'review' && (<Animated.View entering={FadeInUp.duration(300)}>
                  <Text style={styles.heroLine}>REVISIT THE MOMENTS THAT STAYED WITH YOU.</Text><Text style={styles.heroSub}>There are no marks here. Watch back if you can, pause at the moments that changed the match, and give them a name in your own words. We will gently unpack them together.</Text>
                  <HelpCard title="WRITE THIS IMMEDIATELY AFTER FULL TIME">Before you replay or explain the result away, write the turning point in your own words. Then say how you felt and what you believe caused it: pressure, panic, rushing, a forced pass, loss of focus or something else.</HelpCard>
                  <View style={styles.statsSummary}><Text style={styles.statsSummaryLabel}>YOUR TYPED STATS FOR THIS MATCH</Text><View style={styles.statsSummaryRow}><Text style={styles.statsSummaryTxt}>{possession}% poss</Text><Text style={styles.statsSummaryTxt}>{passAcc}% pass</Text><Text style={styles.statsSummaryTxt}>{shots} shots · {shotsOnTarget} on</Text></View><View style={styles.statsSummaryRow}><Text style={styles.statsSummaryTxt}>{corners} corners</Text><Text style={styles.statsSummaryTxt}>{fouls} fouls · {tackles} tackles</Text><Text style={styles.statsSummaryTxt}>{saves} saves</Text></View></View>
                  <View style={styles.momentCard}><Text style={styles.qLabel}>NAME THE MOMENT (YOUR WORDS)</Text><TextInput value={momentName} onChangeText={setMomentName} placeholder="e.g. CONCEDED AFTER A PANIC PASS" placeholderTextColor="rgba(143,184,155,0.35)" style={styles.inputSmall} /><Text style={styles.qLabel}>TIMELINE (MATCH MINUTES)</Text><View style={styles.minRow}><MiniStat label="FROM" value={`${momentStart}’`} /><MiniStat label="TO" value={`${momentEnd}’`} /><View style={styles.minButtons}><Pressable onPress={() => setMomentStart((s) => Math.max(0, s - 1))} style={styles.stepBtn}><Text style={styles.stepBtnTxt}>−</Text></Pressable><Pressable onPress={() => setMomentStart((s) => Math.min(44, s + 1))} style={styles.stepBtn}><Text style={styles.stepBtnTxt}>+</Text></Pressable><Pressable onPress={() => setMomentEnd((e) => Math.max(momentStart + 1, e - 1))} style={styles.stepBtn}><Text style={styles.stepBtnTxt}>−</Text></Pressable><Pressable onPress={() => setMomentEnd((e) => Math.min(45, e + 1))} style={styles.stepBtn}><Text style={styles.stepBtnTxt}>+</Text></Pressable></View></View><Text style={styles.qLabel}>WHAT KIND (OPTIONAL — FEEDS YOUR WEEK SUMMARY)</Text><View style={styles.tagRow}>{BASELINE_MOMENT_TAGS.map((tag) => (<Pressable key={tag} onPress={() => { sfx('pop'); setMoments((prev) => prev.length ? prev.map((m, i) => (i === prev.length - 1 ? { ...m, tag: m.tag === tag ? null : tag } : m)) : [{ id: `BM${Date.now().toString(36)}${(seq.current++).toString(36)}`, name: momentName.trim() || tag, startMin: momentStart, endMin: momentEnd, tag, analysis: {} }]); }} style={[styles.tagChip, moments[moments.length - 1]?.tag === tag && styles.tagChipOn]}><Text style={[styles.tagTxt, moments[moments.length - 1]?.tag === tag && styles.tagTxtOn]}>{tag}</Text></Pressable>))}</View></View>
                  <Pressable onPress={addMoment} style={[styles.cta, momentName.trim().length < 2 && { opacity: 0.35 }]}><Text style={styles.ctaTxt}>ADD THIS MOMENT ›</Text></Pressable>
                  {moments.map((m, i) => (<View key={m.id} style={styles.momentChip}><Text style={styles.momentChipTxt}>{i + 1}. {m.startMin}’–{m.endMin}’ · {m.name.toUpperCase()}{m.tag ? ` · ${m.tag}` : ''}</Text><Pressable hitSlop={8} onPress={() => setMoments((prev) => prev.filter((x) => x.id !== m.id))}><Text style={styles.removeTxt}>✕</Text></Pressable></View>))}
                  <Pressable onPress={() => { sfx('whoosh'); setStep('analysis'); }} style={[styles.cta, moments.length === 0 && { opacity: 0.35 }]}><Text style={styles.ctaTxt}>I’VE NOTED THE MOMENTS — REFLECT ›</Text></Pressable>
                  {moments.length === 0 && (<Text style={styles.requireTxt}>START WITH ONE MOMENT THAT CHANGED THE MATCH — a mistake, a turning point, or something you noticed.</Text>)}
                </Animated.View>)}
              {step === 'analysis' && (<Animated.View entering={FadeInUp.duration(300)}>
                  <Text style={styles.heroLine}>{first} WALKS YOU THROUGH THE MOMENTS.</Text><Text style={styles.heroSub}>This is a private reflection, not an exam — but it is a conversation. Answer him like he is across the table; he reads every word.</Text>
                  <View style={styles.dayIntro}><Image source={coach.portrait} style={styles.beatFace} /><Text style={styles.dayIntroTxt}>{script.analysisIntro}</Text></View>
                  {moments.map((m, mi) => (<View key={m.id} style={styles.analysisBlock}><View style={styles.analysisHead}><EyeIcon size={12} color={colors.accent} /><Text style={styles.analysisHeadTxt}>MOMENT {mi + 1} · {m.startMin}’–{m.endMin}’ · {m.name.toUpperCase()}</Text></View><View style={styles.armNote}><Text style={styles.armNoteTxt}>THE CHINEDU WAY: Have the notes you wrote immediately after full time in front of you. Type your truth about what happened, how you felt and what you believe caused it.</Text></View>{BASELINE_MOMENT_QUESTIONS.map((q, qi) => (<View key={q.key}><Text style={styles.interludeTxt}>{script.momentInterludes[qi] ? `— ${script.momentInterludes[qi]} —` : ''}</Text><View style={styles.askRow}><Image source={coach.portrait} style={styles.askFace} /><Text style={styles.askTxt}>{momentAskFor(script, q.key, qi > 0 ? m.analysis[BASELINE_MOMENT_QUESTIONS[qi - 1].key] : undefined)}</Text></View><View style={styles.aqCard}><Text style={styles.aqLabel}>{q.label}</Text>{REFLECTION_STARTERS[q.key] && <><Text style={styles.starterLabel}>OPTIONAL STARTING POINT — TAP ONE, THEN EXPLAIN IT IN YOUR OWN WORDS</Text><View style={styles.starterRow}>{REFLECTION_STARTERS[q.key]!.map((starter) => <Pressable key={starter} onPress={() => { const current = m.analysis[q.key] ?? ''; if (!current.trim()) setMomentAnalysis(m.id, q.key, q.key === 'feel' ? `I felt ${starter.toLowerCase()} because ` : `I think ${starter.toLowerCase()} caused it because `); }} style={[styles.starterChip, (m.analysis[q.key] ?? '').toUpperCase().includes(starter) && styles.starterChipOn]}><Text style={[styles.starterTxt, (m.analysis[q.key] ?? '').toUpperCase().includes(starter) && styles.starterTxtOn]}>{starter}</Text></Pressable>)}</View></>}<TextInput value={m.analysis[q.key] ?? ''} onChangeText={(t) => setMomentAnalysis(m.id, q.key, t)} placeholder="YOUR WORDS — NOBODY ELSE'S" placeholderTextColor="rgba(143,184,155,0.35)" style={styles.inputSmall} multiline /><Text style={styles.aqCount}>{((m.analysis[q.key] ?? '').trim().length) ? 'A real detail makes this more useful.' : 'A few honest words are enough to begin.'}</Text></View></View>))}{momentComplete(m) ? (<Text style={styles.momentDoneTxt}>✓ MOMENT {mi + 1} CAPTURED</Text>) : (<Text style={styles.requireTxt}>Add a little more to any note that still feels unfinished.</Text>)}</View>))}
                  <Pressable onPress={() => { sfx('whoosh'); setStep('dayq'); }} style={[styles.cta, !allMomentsDone && { opacity: 0.35 }]}><Text style={styles.ctaTxt}>REFLECTION COMPLETE — ONE FINAL CHECK-IN ›</Text></Pressable>
                </Animated.View>)}
              {step === 'dayq' && (<Animated.View entering={FadeInUp.duration(300)}>
                  <Text style={styles.heroLine}>ONE FINAL CHECK-IN FOR DAY {day}.</Text><Text style={styles.questionPick}>{first}’S QUESTION — CHOSEN FOR THIS {result === 'W' ? 'WIN' : result === 'D' ? 'DRAW' : 'DEFEAT'}</Text>
                  <View style={[styles.questionCard, { marginTop: 8 }]}><Image source={coach.portrait} style={styles.beatFace} /><View style={{ flex: 1 }}><Text style={styles.questionIntroTxt}>{script.dayQuestionIntro[result]}</Text><Text style={styles.questionTxt}>{question}</Text></View></View>
                  <HelpCard>Use a real example from this match. We are looking for the pattern behind the result, not the answer that sounds strongest.</HelpCard>
                  <TextInput value={dayAnswer} onChangeText={(t) => setDayAnswer(t.slice(0, 500))} placeholder="A SHORT, HONEST NOTE IN YOUR OWN WORDS." placeholderTextColor={colors.muted} style={styles.input} multiline maxLength={500} />
                  <HonestyBadge text={dayAnswer} options={{ minLength: MIN_ANSWER, minWords: 2, prompt: question }} defaultNote={`YOUR WORDS, YOUR TRUTH — ${first} READS THIS`} coachId={coach.id} />
                  <View style={styles.statsSummary}><Text style={styles.statsSummaryLabel}>DAY {day} RECEIPT — WILL BE AVERAGED INTO YOUR CARD</Text><View style={styles.statsSummaryRow}><Text style={styles.statsSummaryTxt}>{possession}% poss · {passAcc}% pass</Text><Text style={styles.statsSummaryTxt}>{shots}·{shotsOnTarget} shots</Text><Text style={styles.statsSummaryTxt}>{corners} corners · {fouls} fouls</Text></View></View>
                  <Pressable onPress={sealDay} style={[styles.cta, !canSealDay && { opacity: 0.35 }]}><Text style={styles.ctaTxt}>{day >= 5 ? 'SEAL DAY 5 — CONTINUE TO THE WEEK SO FAR' : `SEAL DAY ${day} — CONTINUE TO MATCH ${day + 1}`}</Text></Pressable>
                  {!canSealDay && (<Text style={styles.requireTxt}>Fill stats (8 numbers), one honest moment + analysis, composure and your check-in answer to seal.</Text>)}
                </Animated.View>)}
            </>)}
          {phase === 'reflection' && (<Animated.View entering={FadeInUp.duration(300)}>
              <Text style={styles.eyebrow}>{day === 4 ? `BASELINE WEEK · DAY 4 OF ${BASELINE_DAYS} · REST DAY 1 (NO MATCH TODAY)` : `BASELINE WEEK · DAY 6 OF ${BASELINE_DAYS} · REST DAY 2 (PRE-FINALE PREPARATION)`}</Text><WeekStrip session={session} />
              <Text style={styles.heroLine}>{day === 4 ? 'MOMENTUM IS BUILT. TODAY YOU REST AND REFLECT.' : 'REST AND RECALIBRATE BEFORE THE FINALE.'}</Text><Text style={styles.heroSub}>{day === 4 ? 'Momentum over your first three matches — now you rest. Step away, biro and paper, reflect on patterns.' : 'Tomorrow is your 5th and final baseline match. Today you rest. Set your non-negotiable standards for the finale.'}</Text>
              <View style={styles.receiptBox}><Text style={styles.receiptTag}>THE MOMENTS YOU NAMED SO FAR</Text>{allWeekMoments.length === 0 && <Text style={styles.receiptEmpty}>None yet — the week is waiting.</Text>}{session?.entries.map((e, ei) => (<View key={ei} style={styles.receiptEntry}><Text style={styles.receiptEntryHead}>MATCH {ei + 1} · {e.result} {e.gf}–{e.ga} · HEAD {e.composure}/5{(e.stats ? ` · ${e.stats.possession}% poss · ${e.stats.shots} shots` : '')}</Text>{(e.moments ?? []).map((m) => (<Text key={m.id} style={styles.receiptMoment}>· {m.startMin}’–{m.endMin}’ {m.name.toUpperCase()}{m.tag ? ` — ${m.tag}` : ''}</Text>))}</View>))}{tendencies.length > 0 && (<View style={styles.tendencyWrap}><Text style={styles.receiptTag}>WHAT KEEPS APPEARING</Text><View style={styles.tendencyRow}>{tendencies.map((t) => (<View key={t} style={styles.tendencyPill}><Text style={styles.tendencyTxt}>{t}</Text></View>))}</View></View>)}
              {avgStatsPreview && <View style={styles.tendencyWrap}><Text style={styles.receiptTag}>YOUR RUNNING AVERAGES</Text><Text style={styles.receiptMoment}>{avgStatsPreview.possession}% possession · {avgStatsPreview.passAccuracy}% pass · {avgStatsPreview.shots} shots ({avgStatsPreview.shotsOnTarget} on)</Text></View>}
              </View>
              <Text style={styles.fieldLabel}>{day === 4 ? 'WHAT PATTERN HAVE YOU REPEATED ACROSS MATCHES 1–3?' : 'WHAT DO YOU KEEP REPEATING ACROSS MATCHES 1–4?'}</Text><TextInput value={reflection.repeated} onChangeText={(t) => setReflection((r) => ({ ...r, repeated: t }))} placeholder="LOOK AT THE MOMENTS ABOVE. THE PATTERN IS YOURS." placeholderTextColor={colors.muted} style={styles.input} multiline /><HonestyBadge text={reflection.repeated} options={{ minLength: MIN_ANSWER, minWords: 2 }} defaultNote="NAMING THE REPETITION IS THE FIRST STEP TO CLOSING IT" coachId={coach.id} />
              <Text style={styles.fieldLabel}>{day === 4 ? 'HOW WILL YOU BREAK THIS PATTERN IN MATCH 4 TOMORROW?' : 'WHAT IS YOUR ONE NON-NEGOTIABLE STANDARD FOR THE FINALE TOMORROW?'}</Text><TextInput value={reflection.changed} onChangeText={(t) => setReflection((r) => ({ ...r, changed: t }))} placeholder="IN YOUR DECISIONS, NOT YOUR RESULTS — BE HONEST." placeholderTextColor={colors.muted} style={styles.input} multiline /><HonestyBadge text={reflection.changed} options={{ minLength: MIN_ANSWER, minWords: 2 }} defaultNote="IN YOUR DECISIONS, NOT YOUR RESULTS — BE HONEST" coachId={coach.id} />
              <Pressable onPress={sealReflection} style={[styles.cta, (!isValidReflection(reflection.repeated, { minLength: MIN_ANSWER, minWords: 2 }) || !isValidReflection(reflection.changed, { minLength: MIN_ANSWER, minWords: 2 })) && { opacity: 0.35 }]}><Text style={styles.ctaTxt}>{day === 4 ? 'SEAL REST DAY 1 — CONTINUE TO MATCH 4' : 'SEAL REST DAY 2 — CONTINUE TO MATCH 5 (THE FINALE)'}</Text></Pressable>
            </Animated.View>)}
          {phase === 'ambition' && (<>
              <Text style={styles.eyebrow}>BASELINE WEEK · DAY 7 · THE LAST QUESTION</Text><WeekStrip session={session} /><View style={styles.coachRow}><Image source={coach.portrait} style={styles.coachFace} /><Text style={styles.beatTxt}>{script.ambitionAsk}</Text></View>
              <View style={styles.photoPickBox}><Text style={styles.photoPickLabel}>YOUR CARD PHOTO — LAST CHANCE</Text><Text style={styles.photoPickHint}>This is the photo on your sealed baseline card. Snap it now if you haven’t.</Text>{profilePicUri ? <Image source={{ uri: profilePicUri! }} style={styles.photoPreview} /> : <View style={styles.photoPlaceholder}><Text style={styles.photoPlaceholderTxt}>NO PHOTO YET — YOUR CARD NEEDS YOU</Text></View>}<View style={styles.photoRow}><Pressable onPress={takeProfilePhoto} style={styles.photoBtn}><Text style={styles.photoBtnTxt}>TAKE PHOTO</Text></Pressable><Pressable onPress={pickProfilePic} style={styles.photoBtnAlt}><Text style={styles.photoBtnAltTxt}>PICK GALLERY</Text></Pressable></View></View>
              <TextInput value={ambition} onChangeText={(t) => setAmbition(t.slice(0, 240))} placeholder="WHERE IS YOUR GAME GOING? THE REAL ANSWER." placeholderTextColor={colors.muted} style={styles.input} multiline maxLength={240} /><HonestyBadge text={ambition} options={{ minLength: MIN_ANSWER, minWords: 2 }} defaultNote="HE WILL BRING THIS BACK UP — COUNT ON IT" coachId={coach.id} />
              <Pressable onPress={() => void seal()} style={[styles.cta, !isValidReflection(ambition, { minLength: MIN_ANSWER, minWords: 2 }) && { opacity: 0.35 }]}><Text style={styles.ctaTxt}>{sealing ? 'SEALING…' : 'SEAL MY BASELINE CARD'}</Text></Pressable>
            </>)}
          {phase === 'card' && session?.card && (<Animated.View entering={FadeInUp.duration(360)}>
              <Text style={styles.eyebrow}>BASELINE WEEK · SEALED — THIS IS WHERE YOU ARE</Text>
              <View style={[styles.cardBox, { borderColor: coach.cardAccent }]}>{session.card.profilePicUri ? <Image source={{ uri: session.card.profilePicUri! }} style={styles.cardPhoto} /> : <View style={styles.cardPhotoPh}><Text style={styles.cardPhotoPhTxt}>NO PHOTO</Text></View>}<Text style={styles.cardTier}>{session.card.tier}</Text><Text style={styles.cardHandle}>{session.card.handle}</Text><Text style={styles.cardCoach}>UNDER COACH {first} · {session.card.w}–{session.card.d}–{session.card.l} · {session.card.gf}:{session.card.ga} · HEAD {session.card.avgComposure.toFixed(1)}/5</Text>
                {session.card.avgStats && (<View style={styles.avgBlock}><Text style={styles.avgLabel}>YOUR 5-MATCH AVERAGE — THE CONSOLE TRUTH</Text><View style={styles.avgGrid}><View style={styles.avgCell}><Text style={styles.avgVal}>{session.card.avgStats.possession}%</Text><Text style={styles.avgKey}>POSSESSION</Text></View><View style={styles.avgCell}><Text style={styles.avgVal}>{session.card.avgStats.passAccuracy}%</Text><Text style={styles.avgKey}>PASS ACC</Text></View><View style={styles.avgCell}><Text style={styles.avgVal}>{session.card.avgStats.shots}</Text><Text style={styles.avgKey}>SHOTS</Text></View><View style={styles.avgCell}><Text style={styles.avgVal}>{session.card.avgStats.shotsOnTarget}</Text><Text style={styles.avgKey}>ON TARGET</Text></View><View style={styles.avgCell}><Text style={styles.avgVal}>{session.card.avgStats.corners}</Text><Text style={styles.avgKey}>CORNERS</Text></View><View style={styles.avgCell}><Text style={styles.avgVal}>{session.card.avgStats.fouls}</Text><Text style={styles.avgKey}>FOULS</Text></View><View style={styles.avgCell}><Text style={styles.avgVal}>{session.card.avgStats.tackles}</Text><Text style={styles.avgKey}>TACKLES</Text></View><View style={styles.avgCell}><Text style={styles.avgVal}>{session.card.avgStats.saves}</Text><Text style={styles.avgKey}>SAVES</Text></View></View></View>)}
                <View style={styles.cardStatsGami}>{session.card.cardStats.map((s) => (<View key={s.key} style={styles.gamiStat}><View style={styles.gamiBar}><View style={[styles.gamiFill, { width: `${Math.max(6, s.value)}%`, backgroundColor: gradeColor(s.value) }]} /></View><Text style={styles.gamiLabel}>{s.label} {s.value}</Text></View>))}</View>
                <Text style={styles.cardReadLabel}>{first}'S READ:</Text><Text style={styles.cardReadTxt}>“{session.card.coachRead}”</Text>
                {(session.card.tendencies?.length ?? 0) > 0 && (<><Text style={styles.cardAmbLabel}>WHAT THE WEEK LEARNED ABOUT YOU:</Text><View style={styles.tendencyRow}>{session.card.tendencies.map((t) => (<View key={t} style={styles.tendencyPill}><Text style={styles.tendencyTxt}>{t}</Text></View>))}</View><Text style={styles.tendencyNote}>YOUR TENDENCIES UNDER PRESSURE — THE FIRST THING YOUR MAIN QUESTS WILL WORK ON.</Text></>)}
                <Text style={styles.cardAmbLabel}>YOUR AMBITION (HE REMEMBERS):</Text><Text style={styles.cardAmbTxt}>“{session.card.ambition}”</Text></View>
              <View style={styles.nextBox}><Text style={styles.nextLabel}>BASELINE COMPLETE — FOUNDERS WEEK NEXT</Text><Text style={styles.nextText}>Your average is sealed. Next: the academy tutorial and the pricing discussion with the founder. You have 3 days after pricing to pay and continue.</Text></View>
              <Pressable onPress={onDone} style={styles.cta}><CheckIcon size={12} color="#0a0f0a" /><Text style={styles.ctaTxt}>CARD SEALED — CONTINUE TO FOUNDERS WEEK</Text></Pressable>
            </Animated.View>)}
          {complete && !session?.card && phase !== 'ambition' && phase !== 'card' && (<Text style={styles.requireTxt}>THE WEEK IS COMPLETE — ONE LAST QUESTION AWAITS.</Text>)}
        </Animated.View>
      </ScrollView>
    </View>);
}
function MiniStat({ label, value }: { label: string; value: string }) { return (<View style={styles.miniStat}><Text style={styles.miniStatLabel}>{label}</Text><Text style={styles.miniStatValue}>{value}</Text></View>); }
const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.bg }, scroll: { paddingHorizontal: 20, paddingTop: 8, paddingBottom: 42 }, eyebrow: { color: colors.muted, fontFamily: monoFont, fontSize: 9, letterSpacing: 2, textAlign: 'center' }, title: { color: colors.fg, fontFamily: displayFont, fontSize: 34, lineHeight: 35, letterSpacing: 0.8, textAlign: 'center', marginTop: 8 }, sub: { color: colors.accent, fontFamily: monoFont, fontSize: 9, letterSpacing: 2, textAlign: 'center', marginTop: 8, marginBottom: 6 }, coachRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 16, marginBottom: 4 }, coachFace: { width: 44, height: 44, borderRadius: 22, borderWidth: 1.5, borderColor: colors.border, backgroundColor: colors.surface }, coachName: { color: colors.muted, fontFamily: monoFont, fontSize: 10, letterSpacing: 1.6 }, beat: { flexDirection: 'row', marginTop: 12, gap: 12 }, quoteBar: { width: 3, borderRadius: 2, opacity: 0.6 }, beatTxt: { flex: 1, color: '#dbe7dd', fontFamily: bodyFont, fontSize: 13, lineHeight: 20 }, bluffBox: { marginTop: 18, borderWidth: 1, borderColor: colors.border, borderRadius: 12, backgroundColor: colors.surface, padding: 14 }, bluffLabel: { color: colors.accent, fontFamily: monoFont, fontSize: 8.5, letterSpacing: 2 }, bluffTxt: { color: '#dbe7dd', fontFamily: bodyFont, fontSize: 12.5, lineHeight: 19, marginTop: 6 }, cta: { marginTop: 20, backgroundColor: colors.primary, borderRadius: 25, paddingVertical: 15, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 }, ctaTxt: { color: '#0a0f0a', fontFamily: bodyFontHeavy, fontSize: 13.5, letterSpacing: 0.8 }, skipLink: { color: colors.muted, fontFamily: bodyFont, fontSize: 11.5, letterSpacing: 0.4, textAlign: 'center', marginTop: 14 }, notReadyTxt: { color: colors.muted, fontFamily: bodyFont, fontSize: 12, lineHeight: 18, marginTop: 10, textAlign: 'center' },
  guideBox: { marginTop: 12, borderWidth: 1, borderColor: 'rgba(57,255,106,0.55)', borderRadius: 13, backgroundColor: 'rgba(14,30,18,0.98)', padding: 13 }, guideArrow: { color: colors.primary, fontSize: 23, lineHeight: 22, textAlign: 'center' }, guideCopy: { marginTop: 3 }, guideKicker: { color: colors.primary, fontFamily: monoFont, fontSize: 7, fontWeight: '900', letterSpacing: 1.7 }, guideTitle: { color: colors.fg, fontFamily: monoFont, fontSize: 11, fontWeight: '900', letterSpacing: 1, marginTop: 5 }, guideBody: { color: '#b9cabe', fontFamily: bodyFont, fontSize: 11, lineHeight: 16, marginTop: 5 }, guideActions: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 12 }, guideBack: { color: colors.muted, fontFamily: monoFont, fontSize: 8, letterSpacing: 1 }, guideNext: { backgroundColor: colors.primary, paddingHorizontal: 13, paddingVertical: 8, borderRadius: 15 }, guideNextTxt: { color: '#0a0f0a', fontFamily: monoFont, fontSize: 8, fontWeight: '900', letterSpacing: 1 }, guideSkip: { color: colors.muted, fontFamily: monoFont, fontSize: 7.5, textAlign: 'right', letterSpacing: 1, marginTop: 9 }, replayGuide: { color: colors.primary, fontFamily: monoFont, fontSize: 7.5, textAlign: 'center', letterSpacing: 1.2, marginTop: 10 },
  helpCard: { marginTop: 12, borderLeftWidth: 2, borderLeftColor: colors.accent, borderRadius: 8, backgroundColor: 'rgba(242,192,120,0.07)', padding: 11 }, helpTitle: { color: colors.accent, fontFamily: monoFont, fontSize: 7.5, fontWeight: '900', letterSpacing: 1.4 }, helpText: { color: '#cbd8cf', fontFamily: bodyFont, fontSize: 10.5, lineHeight: 15, marginTop: 5 },
  nextBox: { marginTop: 14, borderWidth: 1, borderColor: 'rgba(57,255,106,0.3)', borderRadius: 12, backgroundColor: 'rgba(57,255,106,0.06)', padding: 12 }, nextLabel: { color: colors.primary, fontFamily: monoFont, fontSize: 7.5, fontWeight: '900', letterSpacing: 1.5 }, nextText: { color: '#cbd8cf', fontFamily: bodyFont, fontSize: 10.5, lineHeight: 15, marginTop: 5 },
  weekStrip: { flexDirection: 'row', justifyContent: 'center', gap: 6, marginTop: 14, marginBottom: 4 }, dayPill: { width: 26, height: 26, borderRadius: 13, borderWidth: 1, alignItems: 'center', justifyContent: 'center' }, dayPillDone: { backgroundColor: 'rgba(57,255,106,0.15)', borderColor: colors.primary }, dayPillNow: { backgroundColor: colors.primary, borderColor: colors.primary }, dayPillLocked: { backgroundColor: colors.surface, borderColor: 'rgba(143,184,155,0.4)' }, dayPillFuture: { backgroundColor: 'transparent', borderColor: 'rgba(143,184,155,0.15)' }, dayPillTxt: { fontFamily: monoFont, fontSize: 9.5, fontWeight: '800' }, dayPillTxtDone: { color: colors.primary }, dayPillTxtNow: { color: '#0a0f0a' }, dayPillTxtMuted: { color: 'rgba(143,184,155,0.6)' },
  heroLine: { marginTop: 16, fontFamily: monoFont, fontSize: 12.5, fontWeight: '900', letterSpacing: 1.2, lineHeight: 18, color: colors.primary }, heroSub: { marginTop: 7, fontSize: 10, lineHeight: 15, color: '#9db4a3' }, dayIntro: { flexDirection: 'row', gap: 10, marginTop: 12, borderWidth: 1, borderColor: colors.border, borderRadius: 14, backgroundColor: colors.surface, padding: 12, alignItems: 'flex-start' }, dayIntroTxt: { flex: 1, color: colors.warm, fontFamily: monoFont, fontSize: 11, lineHeight: 17, letterSpacing: 0.3 }, armNote: { marginTop: 12, borderWidth: 1, borderColor: colors.border, borderRadius: 11, backgroundColor: colors.surface, padding: 12 }, armNoteTxt: { fontSize: 9.5, lineHeight: 14, color: '#9db4a3' },
  scoreCard: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderWidth: 1, borderColor: colors.border, borderRadius: 14, backgroundColor: colors.surface, paddingVertical: 16, paddingHorizontal: 20, marginTop: 14 }, scoreSide: { alignItems: 'center' }, scoreLabel: { color: colors.muted, fontFamily: monoFont, fontSize: 9, letterSpacing: 2, marginBottom: 8 }, stepper: { flexDirection: 'row', alignItems: 'center', gap: 12 }, stepBtn: { width: 34, height: 34, borderRadius: 9, borderWidth: 1, borderColor: colors.border, alignItems: 'center', justifyContent: 'center' }, stepBtnTxt: { color: colors.fg, fontFamily: monoFont, fontSize: 16 }, stepValue: { color: colors.fg, fontFamily: monoFont, fontSize: 22, fontWeight: '700', minWidth: 22, textAlign: 'center' }, pill: { width: 40, height: 40, borderRadius: 20, borderWidth: 1, borderColor: colors.border, alignItems: 'center', justifyContent: 'center' }, pillW: { borderColor: colors.primary, backgroundColor: 'rgba(57,255,106,0.08)' }, pillD: { borderColor: colors.muted }, pillL: { borderColor: colors.loss, backgroundColor: 'rgba(224,96,92,0.08)' }, pillTxt: { color: colors.fg, fontFamily: monoFont, fontSize: 13, fontWeight: '700' }, beatBubble: { flexDirection: 'row', gap: 10, marginTop: 14, borderWidth: 1, borderColor: colors.border, borderRadius: 14, backgroundColor: colors.surface, padding: 12, alignItems: 'flex-start' }, beatFace: { width: 34, height: 34, borderRadius: 17, borderWidth: 1, borderColor: colors.border }, beatBubbleTxt: { flex: 1, color: colors.warm, fontFamily: monoFont, fontSize: 11, lineHeight: 17, letterSpacing: 0.3 },
  fieldLabel: { color: colors.muted, fontFamily: monoFont, fontSize: 9, letterSpacing: 2, marginTop: 18, marginBottom: 8 }, chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, chip: { borderWidth: 1, borderColor: colors.border, borderRadius: 9, paddingHorizontal: 12, paddingVertical: 8, backgroundColor: colors.surface }, chipActive: { borderColor: colors.primary, backgroundColor: 'rgba(57,255,106,0.1)' }, chipTxt: { color: colors.muted, fontFamily: monoFont, fontSize: 9.5, letterSpacing: 1 }, chipTxtActive: { color: colors.primary }, requireTxt: { color: colors.muted, fontFamily: monoFont, fontSize: 8.5, letterSpacing: 1.4, marginTop: 12, textAlign: 'center' },
  // stats typing
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 12 }, statField: { width: '48.5%', borderWidth: 1, borderColor: colors.border, borderRadius: 11, backgroundColor: colors.surface, padding: 10 }, statFieldHead: { marginBottom: 6 }, statLabel: { color: colors.fg, fontFamily: monoFont, fontSize: 8.5, fontWeight: '900', letterSpacing: 1.2 }, statHint: { color: colors.muted, fontFamily: monoFont, fontSize: 6.5, letterSpacing: 0.8, marginTop: 2 }, statInputRow: { flexDirection: 'row', alignItems: 'center', gap: 6 }, statInput: { flex: 1, borderWidth: 1, borderColor: 'rgba(57,255,106,0.18)', borderRadius: 8, backgroundColor: '#0a0f0a', color: colors.fg, fontFamily: monoFont, fontSize: 16, fontWeight: '700', paddingHorizontal: 10, paddingVertical: 10, textAlign: 'center' }, statSuffix: { color: colors.muted, fontFamily: monoFont, fontSize: 11, fontWeight: '700', minWidth: 12 },
  statsNote: { marginTop: 10, borderRadius: 9, backgroundColor: 'rgba(242,192,120,0.08)', borderWidth: 1, borderColor: 'rgba(242,192,120,0.2)', padding: 10 }, statsNoteTxt: { color: colors.warm, fontFamily: bodyFont, fontSize: 10, lineHeight: 15 },
  statsSummary: { marginTop: 12, borderWidth: 1, borderColor: 'rgba(57,255,106,0.2)', borderRadius: 11, backgroundColor: 'rgba(57,255,106,0.06)', padding: 10 }, statsSummaryLabel: { color: colors.primary, fontFamily: monoFont, fontSize: 6.5, fontWeight: '900', letterSpacing: 1.4 }, statsSummaryRow: { flexDirection: 'row', gap: 8, marginTop: 6, flexWrap: 'wrap' }, statsSummaryTxt: { color: '#cbd8cf', fontFamily: monoFont, fontSize: 7.5, letterSpacing: 0.6 },
  photoPickBox: { marginTop: 14, borderWidth: 1, borderColor: colors.border, borderRadius: 12, backgroundColor: colors.surface, padding: 12 }, photoPickBoxSmall: { marginTop: 12, borderWidth: 1, borderColor: 'rgba(57,255,106,0.22)', borderRadius: 12, backgroundColor: 'rgba(57,255,106,0.05)', padding: 12 }, photoPickLabel: { color: colors.accent, fontFamily: monoFont, fontSize: 7.5, fontWeight: '900', letterSpacing: 1.4 }, photoPickHint: { color: colors.muted, fontFamily: bodyFont, fontSize: 10, lineHeight: 14, marginTop: 4 }, photoPreview: { width: 120, height: 120, borderRadius: 60, marginTop: 10, alignSelf: 'center', borderWidth: 2, borderColor: colors.primary }, photoPreviewSmall: { width: 80, height: 80, borderRadius: 40, marginTop: 10, alignSelf: 'center', borderWidth: 1.5, borderColor: colors.primary }, photoPlaceholder: { marginTop: 10, height: 90, borderRadius: 10, borderWidth: 1, borderColor: 'rgba(143,184,155,0.22)', borderStyle: 'dashed', alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(10,20,13,0.5)' }, photoPlaceholderSmall: { marginTop: 10, height: 64, borderRadius: 10, borderWidth: 1, borderColor: 'rgba(143,184,155,0.22)', borderStyle: 'dashed', alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(10,20,13,0.5)' }, photoPlaceholderTxt: { color: colors.muted, fontFamily: monoFont, fontSize: 7, letterSpacing: 1 }, photoRow: { flexDirection: 'row', gap: 8, marginTop: 10 }, photoBtn: { flex: 1, backgroundColor: colors.primary, borderRadius: 10, paddingVertical: 11, alignItems: 'center' }, photoBtnTxt: { color: '#0a0f0a', fontFamily: monoFont, fontSize: 8.5, fontWeight: '900', letterSpacing: 1 }, photoBtnAlt: { flex: 1, borderWidth: 1, borderColor: colors.border, borderRadius: 10, paddingVertical: 11, alignItems: 'center', backgroundColor: colors.surface }, photoBtnAltTxt: { color: colors.fg, fontFamily: monoFont, fontSize: 8.5, fontWeight: '900', letterSpacing: 1 }, photoBtnSmall: { flex: 1, backgroundColor: colors.primary, borderRadius: 9, paddingVertical: 9, alignItems: 'center' }, photoBtnAltSmall: { flex: 1, borderWidth: 1, borderColor: colors.border, borderRadius: 9, paddingVertical: 9, alignItems: 'center', backgroundColor: colors.surface },
  markRow: { flexDirection: 'row', gap: 10, marginTop: 10 }, markBtn: { flex: 1, height: 42, borderRadius: 10, borderWidth: 1, borderColor: 'rgba(242,192,120,0.5)', backgroundColor: 'rgba(38,30,12,0.5)', alignItems: 'center', justifyContent: 'center' }, markBtnTxt: { fontFamily: monoFont, fontSize: 7, fontWeight: '900', letterSpacing: 1.2, color: colors.accent }, momentCard: { marginTop: 14, borderWidth: 1, borderColor: colors.border, borderRadius: 12, backgroundColor: colors.surface, padding: 13 }, qLabel: { fontFamily: monoFont, fontSize: 7.2, fontWeight: '800', letterSpacing: 1.2, color: colors.fg, lineHeight: 11, marginTop: 10 }, inputSmall: { marginTop: 7, borderWidth: 1, borderColor: 'rgba(57,255,106,0.18)', borderRadius: 8, backgroundColor: '#0a0f0a', color: colors.fg, fontFamily: monoFont, fontSize: 11, lineHeight: 17, padding: 10, minHeight: 42, textAlignVertical: 'top' }, minRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 10 }, minButtons: { flexDirection: 'row', gap: 6, marginLeft: 'auto' }, miniStat: { flex: 1, borderWidth: 1, borderColor: 'rgba(57,255,106,0.25)', borderRadius: 10, backgroundColor: 'rgba(10,20,13,0.8)', paddingVertical: 10, alignItems: 'center', gap: 4 }, miniStatLabel: { fontFamily: monoFont, fontSize: 5.4, letterSpacing: 1.4, color: 'rgba(143,184,155,0.65)' }, miniStatValue: { fontFamily: monoFont, fontSize: 9, fontWeight: '900', letterSpacing: 1, color: colors.primary }, tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginTop: 8 }, tagChip: { borderWidth: 1, borderColor: colors.border, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 6, backgroundColor: colors.surface }, tagChipOn: { borderColor: colors.accent, backgroundColor: 'rgba(242,192,120,0.1)' }, tagTxt: { color: colors.muted, fontFamily: monoFont, fontSize: 7.5, letterSpacing: 1 }, tagTxtOn: { color: colors.accent }, momentChip: { marginTop: 8, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderWidth: 1, borderColor: 'rgba(57,255,106,0.25)', borderRadius: 9, backgroundColor: 'rgba(10,20,13,0.7)', paddingHorizontal: 11, paddingVertical: 9 }, momentChipTxt: { fontFamily: monoFont, fontSize: 6.8, letterSpacing: 0.9, color: '#c4d4c8', flex: 1 }, removeTxt: { color: colors.loss, fontFamily: monoFont, fontSize: 11 },
  starterLabel: { color: colors.muted, fontFamily: monoFont, fontSize: 6.5, letterSpacing: 0.8, lineHeight: 10, marginTop: 8 }, starterRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 6 }, starterChip: { borderWidth: 1, borderColor: 'rgba(143,184,155,0.35)', borderRadius: 9, paddingHorizontal: 8, paddingVertical: 5, backgroundColor: 'rgba(10,20,13,0.7)' }, starterChipOn: { borderColor: colors.primary, backgroundColor: 'rgba(57,255,106,0.1)' }, starterTxt: { color: '#b9cabe', fontFamily: monoFont, fontSize: 6.5, letterSpacing: 0.7 }, starterTxtOn: { color: colors.primary },
  analysisBlock: { marginTop: 16, borderWidth: 1, borderColor: 'rgba(242,192,120,0.4)', borderRadius: 13, backgroundColor: 'rgba(20,18,10,0.6)', padding: 12 }, analysisHead: { flexDirection: 'row', alignItems: 'center', gap: 7 }, analysisHeadTxt: { color: colors.accent, fontFamily: monoFont, fontSize: 8, letterSpacing: 1.6, fontWeight: '700', flex: 1 }, askRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, marginTop: 14 }, askFace: { width: 22, height: 22, borderRadius: 11, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, marginTop: 1 }, askTxt: { flex: 1, color: colors.warm, fontFamily: bodyFont, fontStyle: 'italic', fontSize: 11.5, lineHeight: 17 }, interludeTxt: { marginTop: 16, color: 'rgba(157,180,163,0.75)', fontFamily: bodyFont, fontStyle: 'italic', fontSize: 10, textAlign: 'center', letterSpacing: 0.3 }, aqCard: { marginTop: 6 }, aqLabel: { fontFamily: monoFont, fontSize: 7.4, fontWeight: '800', letterSpacing: 1.1, color: colors.fg, lineHeight: 11 }, aqCount: { marginTop: 4, fontFamily: monoFont, fontSize: 6.5, letterSpacing: 1, color: 'rgba(143,184,155,0.6)', textAlign: 'right' }, momentDoneTxt: { marginTop: 10, fontFamily: monoFont, fontSize: 7.5, fontWeight: '900', letterSpacing: 1.4, color: colors.primary, textAlign: 'center' }, playTxt: { marginTop: 8, fontFamily: monoFont, fontSize: 7.6, fontWeight: '900', letterSpacing: 1, color: colors.primary },
  questionPick: { color: colors.accent, fontFamily: monoFont, fontSize: 7.5, fontWeight: '900', letterSpacing: 1.6, marginTop: 14 }, questionCard: { flexDirection: 'row', gap: 10, marginTop: 14, borderWidth: 1, borderColor: colors.border, borderRadius: 14, backgroundColor: colors.surface, padding: 12, alignItems: 'flex-start' }, questionIntroTxt: { color: '#b9cabe', fontFamily: bodyFont, fontStyle: 'italic', fontSize: 10.5, lineHeight: 16, marginBottom: 6 }, questionTxt: { flex: 1, color: colors.fg, fontFamily: monoFont, fontSize: 13, lineHeight: 20, letterSpacing: 0.3 }, input: { marginTop: 10, borderWidth: 1, borderColor: colors.border, backgroundColor: '#0a0f0a', borderRadius: 12, color: colors.fg, fontFamily: monoFont, fontSize: 11.5, lineHeight: 18, padding: 12, minHeight: 90, textAlignVertical: 'top' }, countTxt: { color: colors.muted, fontFamily: monoFont, fontSize: 8.5, letterSpacing: 1.2, marginTop: 6, textAlign: 'right' },
  receiptBox: { marginTop: 14, borderWidth: 1, borderColor: 'rgba(242,192,120,0.4)', borderRadius: 13, backgroundColor: 'rgba(20,18,10,0.5)', padding: 13 }, receiptTag: { fontFamily: monoFont, fontSize: 7, fontWeight: '900', letterSpacing: 1.8, color: colors.accent }, receiptEmpty: { marginTop: 8, fontSize: 10, color: '#9db4a3' }, receiptEntry: { marginTop: 10 }, receiptEntryHead: { fontFamily: monoFont, fontSize: 7.5, fontWeight: '900', letterSpacing: 1.2, color: colors.primary }, receiptMoment: { marginTop: 4, fontFamily: monoFont, fontSize: 7.2, letterSpacing: 0.8, color: '#c4d4c8' }, tendencyWrap: { marginTop: 14 }, tendencyRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 8, alignSelf: 'flex-start' }, tendencyPill: { borderWidth: 1, borderColor: colors.border, borderRadius: 8, paddingHorizontal: 9, paddingVertical: 5, backgroundColor: 'rgba(242,192,120,0.06)' }, tendencyTxt: { color: colors.accent, fontFamily: monoFont, fontSize: 8.5, letterSpacing: 1.2, fontWeight: '700' }, tendencyNote: { marginTop: 7, color: colors.muted, fontFamily: monoFont, fontSize: 7.5, letterSpacing: 1, alignSelf: 'flex-start' },
  cardBox: { marginTop: 16, borderWidth: 1.5, borderRadius: 18, backgroundColor: colors.surface, padding: 20, alignItems: 'center' }, cardTier: { color: colors.accent, fontFamily: monoFont, fontSize: 20, fontWeight: '800', letterSpacing: 3 }, cardHandle: { color: colors.fg, fontFamily: monoFont, fontSize: 14, letterSpacing: 1.6, marginTop: 8 }, cardCoach: { color: colors.muted, fontFamily: monoFont, fontSize: 9, letterSpacing: 1.6, marginTop: 4 }, cardPhoto: { width: 88, height: 88, borderRadius: 44, borderWidth: 2, borderColor: colors.primary, marginBottom: 12 }, cardPhotoPh: { width: 88, height: 88, borderRadius: 44, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.bg, alignItems: 'center', justifyContent: 'center', marginBottom: 12 }, cardPhotoPhTxt: { color: colors.muted, fontFamily: monoFont, fontSize: 8, letterSpacing: 1 }, avgBlock: { marginTop: 14, width: '100%', borderWidth: 1, borderColor: 'rgba(57,255,106,0.18)', borderRadius: 12, backgroundColor: 'rgba(10,20,13,0.6)', padding: 12 }, avgLabel: { color: colors.primary, fontFamily: monoFont, fontSize: 6.5, fontWeight: '900', letterSpacing: 1.5, textAlign: 'center' }, avgGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 10 }, avgCell: { width: '22%', minWidth: 64, alignItems: 'center', borderWidth: 1, borderColor: 'rgba(143,184,155,0.15)', borderRadius: 9, backgroundColor: 'rgba(255,255,255,0.03)', paddingVertical: 8 }, avgVal: { color: colors.fg, fontFamily: monoFont, fontSize: 11, fontWeight: '800' }, avgKey: { color: colors.muted, fontFamily: monoFont, fontSize: 5.5, letterSpacing: 1, marginTop: 3 }, cardStats: { flexDirection: 'row', marginTop: 18, width: '100%', justifyContent: 'space-around' }, cardStatsGami: { marginTop: 14, width: '100%', gap: 6 }, gamiStat: { flexDirection: 'row', alignItems: 'center', gap: 8 }, gamiBar: { flex: 1, height: 8, borderRadius: 4, backgroundColor: 'rgba(255,255,255,0.08)', overflow: 'hidden' }, gamiFill: { height: '100%', borderRadius: 4 }, gamiLabel: { color: colors.muted, fontFamily: monoFont, fontSize: 7, letterSpacing: 0.8, width: 110, textAlign: 'right' }, cardStat: { alignItems: 'center' }, cardStatV: { color: colors.fg, fontFamily: monoFont, fontSize: 16, fontWeight: '700' }, cardStatL: { color: colors.muted, fontFamily: monoFont, fontSize: 8, letterSpacing: 1.6, marginTop: 3 }, cardReadLabel: { color: colors.accent, fontFamily: monoFont, fontSize: 8.5, letterSpacing: 2, marginTop: 18, alignSelf: 'flex-start' }, cardReadTxt: { color: colors.fg, fontFamily: monoFont, fontSize: 11, lineHeight: 17, fontStyle: 'italic', marginTop: 6 }, cardAmbLabel: { color: colors.accent, fontFamily: monoFont, fontSize: 8.5, letterSpacing: 2, marginTop: 14, alignSelf: 'flex-start' }, cardAmbTxt: { color: colors.warm, fontFamily: monoFont, fontSize: 11, lineHeight: 17, fontStyle: 'italic', marginTop: 6 },
});
